# Generated by Django 3.1 on 2020-08-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200817_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
