# Generated by Django 3.1 on 2020-08-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_package_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('name',), name='unique_name_if_not_deleted'),
        ),
    ]
