# Generated by Django 3.1 on 2020-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200829_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packageactivitytask',
            old_name='is_available',
            new_name='is_not_applicable_status_by_default',
        ),
        migrations.AddField(
            model_name='packageactivitytask',
            name='photo_requirement_comment',
            field=models.TextField(null=True),
        ),
    ]
