# Generated by Django 3.1 on 2020-09-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200902_0755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageactivitytask',
            options={'ordering': ('order',)},
        ),
    ]
