# Generated by Django 3.1 on 2020-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200908_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageactivity',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
