# Generated by Django 3.1 on 2020-09-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200908_0825'),
        ('api', '0012_auto_20200907_0841'),
    ]

    operations = [
    ]
