# Generated by Django 3.1 on 2020-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200908_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('tendering', 'Tendering'), ('under_construction', 'Under construction'), ('partially_competed', 'Partially completed'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=255)),
                ('show_estimated_man_hours', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=models.deletion.CASCADE, to='api.media')),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
            ],
            options={
                'db_table': 'projects',
                'ordering': ('name',),
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('name',), name='projects_unique_name_if_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('number',), name='projects_unique_number_if_not_deleted'),
        ),
    ]
