# Generated by Django 3.1 on 2020-09-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200908_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='value',
            field=models.CharField(null=True, max_length=255),
            preserve_default=False,
        ),
    ]
