# Generated by Django 3.1 on 2020-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_projectnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('tendering', 'Tendering'), ('under_construction', 'Under construction'), ('partially_completed', 'Partially completed'), ('completed', 'Completed'), ('archived', 'Archived')], max_length=255),
        ),
    ]
