# Generated by Django 3.1 on 2020-09-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_project_key_contacts'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='packageactivitytask',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('description',), name='package_activity_task_unique_description_if_not_deleted'),
        ),
    ]
