# Generated by Django 3.1 on 2020-09-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200924_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
                ('package_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packageactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'package_matrix',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='package_activities',
            field=models.ManyToManyField(through='api.PackageMatrix', to='api.PackageActivity'),
        ),
        migrations.AddField(
            model_name='package',
            name='projects',
            field=models.ManyToManyField(through='api.PackageMatrix', to='api.Project'),
        ),
        migrations.AddConstraint(
            model_name='packagematrix',
            constraint=models.UniqueConstraint(fields=('project', 'package', 'package_activity'), name='package_matrix_unique'),
        ),
    ]
