# Generated by Django 3.1 on 2020-09-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200928_1217'),
        ('api', '0025_auto_20200925_1007'),
    ]

    operations = [
    ]
