# Generated by Django 3.1 on 2020-09-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_merge_20200929_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMatrixHiddenActivityTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_activity_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packageactivitytask')),
                ('package_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagematrix')),
            ],
            options={
                'db_table': 'package_matrix_hidden_activity_tasks',
            },
        ),
        migrations.AddConstraint(
            model_name='packagematrixhiddenactivitytask',
            constraint=models.UniqueConstraint(fields=('package_matrix', 'package_activity_task'), name='package_matrix_hidden_activity_tasks_unique'),
        ),
    ]
