# Generated by Django 3.1 on 2020-10-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200928_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'location_matrix',
            },
        ),
        migrations.AddConstraint(
            model_name='locationmatrix',
            constraint=models.UniqueConstraint(fields=('building', 'level', 'area', 'project'), name='location_matrix_unique'),
        ),
    ]
