# Generated by Django 3.1 on 2020-10-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201006_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationMatrixPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('location_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locationmatrix')),
                ('package_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagematrix')),
            ],
            options={
                'db_table': 'location_matrix_packages',
            },
        ),
        migrations.AddConstraint(
            model_name='locationmatrixpackage',
            constraint=models.UniqueConstraint(fields=('location_matrix', 'package_matrix'), name='location_matrix_packages_uniqueness'),
        ),
    ]
