# Generated by Django 3.1 on 2020-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20201008_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmatrixpackage',
            name='files',
            field=models.ManyToManyField(to='api.Media'),
        ),
    ]
