# Generated by Django 3.1 on 2020-10-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_locationmatrixpackage_files'),
        ('api', '0030_auto_20201012_1142'),
    ]

    operations = [
    ]
