# Generated by Django 3.1 on 2020-10-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_merge_20201013_0741'),
        ('api', '0031_media_size'),
    ]

    operations = [
    ]
