# Generated by Django 3.1 on 2020-10-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_editmode'),
        ('api', '0034_subtask_files'),
    ]

    operations = [
    ]
