# Generated by Django 3.1 on 2020-10-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20201019_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmatrixpackage',
            name='package',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.package'),
        ),
        migrations.AddField(
            model_name='locationmatrixpackage',
            name='package_activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packageactivity'),
        ),
        migrations.AddField(
            model_name='locationmatrixpackage',
            name='package_activity_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
