# Generated by Django 2.0.5 on 2018-06-18 10:10

import pydash
from django.db import connection, migrations

def get_location_matrix_packages(cursor):
    cursor.execute("SELECT id, package_matrix_id FROM location_matrix_packages WHERE package_id IS NULL AND package_activity_name IS NULL",)

    return cursor.fetchall()

def get_package_matrix_list(cursor):
    cursor.execute("SELECT id, package_id, package_activity_id  FROM package_matrix",)

    return cursor.fetchall()

def get_package_activities_list(cursor):
    cursor.execute("SELECT id, name FROM package_activities",)

    return cursor.fetchall()

def set_location_matrix_package_data(*args, **kwargs):
    with connection.cursor() as cursor:
        location_matrix_packages = get_location_matrix_packages(cursor)
        package_matrix_list = get_package_matrix_list(cursor)
        package_activities_list = get_package_activities_list(cursor)

        for location_matrix_package in location_matrix_packages:
            package_matrix = pydash.find(package_matrix_list, lambda package_matrix: package_matrix[0] == location_matrix_package[1])
            package_activities = pydash.find(package_activities_list, lambda package_activities: package_activities[0] == package_matrix[2])

            cursor.execute('UPDATE location_matrix_packages SET package_id = %s WHERE id = %s', [package_matrix[1], location_matrix_package[0]])
            cursor.execute('UPDATE location_matrix_packages SET package_activity_id = %s WHERE id = %s', [package_activities[0], location_matrix_package[0]])
            cursor.execute('UPDATE location_matrix_packages SET package_activity_name = %s WHERE id = %s', [package_activities[1], location_matrix_package[0]])


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0037_auto_20201023_1437'),
    ]

    operations = [
        migrations.RunPython(set_location_matrix_package_data),
    ]
