# Generated by Django 3.1 on 2020-10-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_set_location_matrix_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmatrixpackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package'),
        ),
        migrations.AlterField(
            model_name='locationmatrixpackage',
            name='package_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packageactivity'),
        ),
        migrations.AlterField(
            model_name='locationmatrixpackage',
            name='package_activity_name',
            field=models.CharField(max_length=255),
        ),
    ]
