# Generated by Django 3.1 on 2020-10-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20201023_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationmatrixpackage',
            old_name='files',
            new_name='media',
        ),
    ]
