# Generated by Django 3.1 on 2020-11-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20201027_0932'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packageactivitytask',
            name='package_activity_task_unique_description_if_not_deleted',
        ),
        migrations.AddConstraint(
            model_name='packageactivitytask',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('package_activity', 'description'), name='package_activity_task_unique_description_if_not_deleted'),
        ),
    ]
