# Generated by Django 3.1.3 on 2020-11-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20201103_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
    ]
