# Generated by Django 3.1.3 on 2020-11-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_taskupdate'),
    ]

    operations = [
        migrations.RunSQL('drop table if exists api_historicaltask cascade;')
    ]
