# Generated by Django 3.1.3 on 2020-11-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_delete_historicaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_approval',
            field=models.DateTimeField(null=True),
        ),
    ]
