# Generated by Django 3.1.3 on 2020-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_task_data_of_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='date_of_completion',
            field=models.DateTimeField(null=True),
        ),
    ]
