# Generated by Django 3.1.3 on 2020-11-13 07:29

from django.db import migrations

def create_through_relations(apps, schema_editor):
    Project = apps.get_model('api', 'Project')
    ProjectUser = apps.get_model('api', 'ProjectUser')

    for project in Project.objects.all():
        for user in project.users.all():
            ProjectUser(
                user=user,
                project=project,
                is_notifications_enabled=False
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_projectuser'),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
