# Generated by Django 3.1.3 on 2020-11-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_subtask_date_of_completion'),
        ('api', '0045_recipient_subtaskupdate'),
    ]

    operations = [
    ]
