# Generated by Django 3.1.3 on 2020-11-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_create_through_relations_for_project_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
