# Generated by Django 3.1.3 on 2020-11-13 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_project_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='api.ProjectUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
