# Generated by Django 3.1.3 on 2020-11-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_merge_20201112_2041'),
        ('api', '0049_project_users'),
    ]

    operations = [
    ]
