# Generated by Django 3.1.3 on 2020-11-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_merge_20201113_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='recipients',
            field=models.ManyToManyField(to='api.Recipient'),
        ),
    ]
