# Generated by Django 3.1.3 on 2020-11-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_taskupdate_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='estimation',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
