# Generated by Django 3.1.3 on 2020-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_add_subcontractor_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
