# Generated by Django 3.1.3 on 2020-11-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_subtask_due_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packagematrix',
            name='package_matrix_unique',
        ),
        migrations.RemoveConstraint(
            model_name='packagematrix',
            name='package_matrix_unique_activity',
        ),
        migrations.AddConstraint(
            model_name='packagematrix',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('project', 'package', 'package_activity'), name='package_matrix_unique'),
        ),
        migrations.AddConstraint(
            model_name='packagematrix',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('project', 'package_activity'), name='package_matrix_unique_activity'),
        ),
    ]
