# Generated by Django 3.1.3 on 2020-11-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20201126_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
