# Generated by Django 3.1.3 on 2020-12-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20201127_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='original_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
