# Generated by Django 3.1.3 on 2020-12-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20201203_1008'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locationmatrix',
            constraint=models.Index(fields=['building', 'level', 'area', 'project'], name='location_matrix_unique'),
        ),
    ]
