# Generated by Django 3.1.3 on 2020-12-09 11:09

import api.models.fields.datetime_field_omit_auto_now_value
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20201203_1100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationmatrixpackage',
            name='location_matrix_packages_uniqueness',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='created_at',
            field=api.models.fields.datetime_field_omit_auto_now_value.DateTimeFieldOmitAutoNowValue(auto_now_add=True),
        ),
        migrations.AddConstraint(
            model_name='locationmatrixpackage',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('location_matrix', 'package_matrix'), name='location_matrix_packages_uniqueness'),
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_uniqueness',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('package_activity', 'package_activity_task', 'location_matrix'), name='tasks_uniqueness'),
        ),
    ]
