# Generated by Django 3.1.3 on 2020-12-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20201209_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageactivity',
            name='activity_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
