# Generated by Django 3.1.4 on 2021-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_packageactivity_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
