# Generated by Django 3.1.4 on 2021-01-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_user_status'),
    ]

    operations = [
        migrations.RunSQL("UPDATE auth_user SET status='approved'")
    ]
