# Generated by Django 3.1.4 on 2021-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_delete_duplicated_recipients'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationmatrix',
            name='location_matrix_unique',
        ),
        migrations.AddConstraint(
            model_name='locationmatrix',
            constraint=models.Index(condition=models.Q(deleted__isnull=True), fields=['building', 'level', 'area', 'project'], name='location_matrix_unique'),
        ),
    ]
