# Generated by Django 3.1.4 on 2021-03-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20210309_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['id']},
        ),
    ]
