# Generated by Django 3.1.4 on 2021-03-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_auto_20210315_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['id']},
        ),
    ]
