# Generated by Django 3.1.4 on 2021-03-17 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20210316_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.company'),
        ),
    ]
