# Generated by Django 2.0.5 on 2018-06-18 10:10

import pydash
from django.db import connection, migrations


def set_user_company_id(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute('UPDATE auth_user u SET company_ref_id = c.id FROM companies c WHERE c.name = u.company;')


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0077_fill_companies_table'),
    ]

    operations = [
        migrations.RunPython(set_user_company_id),
    ]
