# Generated by Django 3.1.4 on 2021-03-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_set_user_company_ref_id_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='company_old',
        ),
    ]
