# Generated by Django 3.1.4 on 2021-03-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20210317_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_ref',
            new_name='company',
        ),
    ]
