# Generated by Django 3.1.4 on 2021-03-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_add_consultant_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
