# Generated by Django 3.1.4 on 2021-03-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_auto_20210318_0717'),
        ('api', '0076_qualityissue'),
    ]

    operations = [
    ]
