# Generated by Django 3.1.4 on 2021-03-19 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_merge_20210318_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityissue',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('removed', 'Removed'), ('contested', 'Contested'), ('in_progress', 'In Progress'), ('requesting_approval', 'Requesting Approval'), ('requested_approval_rejected', 'Requested Approval Rejected'), ('closed_out', 'Closed Out')], default='under_review', max_length=255),
        ),
        migrations.CreateModel(
            name='QualityIssueUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('old_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('files', models.ManyToManyField(to='api.Media')),
                ('quality_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.qualityissue')),
                ('recipients', models.ManyToManyField(to='api.Recipient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_issue_updates',
            },
        ),
    ]
