# Generated by Django 3.1.4 on 2021-03-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20210319_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualityissue',
            options={'ordering': ['id']},
        ),
    ]
