# Generated by Django 3.1.4 on 2021-03-23 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20210323_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='quality_issue',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.qualityissue'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='subcontractor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractors', to=settings.AUTH_USER_MODEL),
        ),
    ]
