# Generated by Django 3.1.4 on 2021-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20210323_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('in_progress', 'In Progress'), ('removed', 'Removed'), ('contested', 'Contested'), ('under_inspection', 'Under Inspection'), ('inspection_rejected', 'Inspection Rejected'), ('requesting_approval', 'Requesting Approval')], default='in_progress', max_length=255),
        ),
    ]
