# Generated by Django 3.1.4 on 2021-03-24 10:41

from django.db import migrations, connection


def fill_subtask_status(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("UPDATE subtasks SET status=CASE WHEN is_closed THEN 'closed' ELSE 'in_progress' END;")


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0087_subtask_status'),
    ]

    operations = [
        migrations.RunPython(fill_subtask_status),
    ]

