# Generated by Django 3.1.4 on 2021-03-25 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_migrate_subtask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='is_closed',
        ),
    ]
