# Generated by Django 3.1.4 on 2021-04-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_remove_subtask_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_defect',
            field=models.BooleanField(default=False),
        ),
    ]
