# Generated by Django 3.1.4 on 2021-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_subtask_is_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityissue',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
