# Generated by Django 3.1.4 on 2021-04-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_qualityissue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageactivitytask',
            name='is_default_for_subtask',
            field=models.BooleanField(default=False),
        ),
    ]
