# Generated by Django 3.1.4 on 2021-04-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_packageactivitytask_is_default_for_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityissue',
            name='last_confirmed_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.qualityissueupdate'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='last_confirmed_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_subtask', to='api.subtaskupdate'),
        ),
    ]
