# Generated by Django 3.1.4 on 2021-04-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20210414_1359'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='packageactivitytask',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('is_default_for_subtask', True)), fields=('package_activity', 'is_default_for_subtask'), name='package_activity_task_unique_default_for_subtask_if_not_deleted'),
        ),
    ]
