# Generated by Django 3.1.4 on 2021-04-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20210424_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='response_due_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
