# Generated by Django 3.1.4 on 2021-04-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_auto_20210424_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityissue',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('removed', 'Removed'), ('contested', 'Contested'), ('in_progress', 'In Progress'), ('requesting_approval', 'Requesting Approval'), ('requested_approval_rejected', 'Requested Approval Rejected'), ('closed_out', 'Closed Out'), ('declined', 'Declined')], default='under_review', max_length=255),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('in_progress', 'In Progress'), ('removed', 'Removed'), ('contested', 'Contested'), ('under_inspection', 'Under Inspection'), ('inspection_rejected', 'Inspection Rejected'), ('requesting_approval', 'Requesting Approval'), ('declined', 'Declined')], default='in_progress', max_length=255),
        ),
    ]
