# Generated by Django 3.1.4 on 2021-04-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_subtask_response_due_date'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE subtasks s 
            SET response_due_date = qi.due_date 
            FROM quality_issue qi
              WHERE s.quality_issue_id = qi.id
        """),
    ]
