# Generated by Django 3.1.4 on 2021-05-01 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_auto_20210429_1230'),
        ('api', '0096_fill_subtask_response_due_date'),
    ]

    operations = [
    ]
