# Generated by Django 3.1.4 on 2021-05-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_merge_20210501_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityissue',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('removed', 'Removed'), ('contested', 'Contested'), ('in_progress', 'In Progress'), ('under_inspection', 'Under Inspection'), ('inspection_rejected', 'Inspection Rejected'), ('requesting_approval', 'Requesting Approval'), ('requested_approval_rejected', 'Requested Approval Rejected'), ('closed_out', 'Closed Out'), ('declined', 'Declined')], default='under_review', max_length=255),
        ),
    ]
