# Generated by Django 3.1.4 on 2021-05-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_merge_20210501_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityissue',
            name='old_quality_issue_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.qualityissue'),
        ),
    ]
