# Generated by Django 3.1.4 on 2021-05-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_qualityissue_old_quality_issue_id'),
        ('api', '0098_auto_20210503_0620'),
    ]

    operations = [
    ]
