# Generated by Django 3.1.4 on 2021-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_migrate_quality_issue_statuses_20210504_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityissue',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('in_progress', 'In Progress'), ('removed', 'Removed'), ('contested', 'Contested'), ('under_inspection', 'Under Inspection'), ('under_review', 'Under Review'), ('inspection_rejected', 'Inspection Rejected'), ('requesting_approval', 'Requesting Approval'), ('requested_approval_rejected', 'Requested Approval Rejected'), ('declined', 'Declined')], default='under_review', max_length=255),
        ),
    ]
