# Generated by Django 3.1.4 on 2021-05-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20210507_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageMatrixCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('package_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagematrix')),
            ],
            options={
                'db_table': 'package_matrix_company',
            },
        ),
        migrations.AddConstraint(
            model_name='packagematrixcompany',
            constraint=models.UniqueConstraint(condition=models.Q(deleted__isnull=True), fields=('package_matrix', 'company'), name='package_matrix_company_unique'),
        ),
    ]
