# Generated by Django 3.1.4 on 2021-05-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20210514_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagematrix',
            name='companies',
            field=models.ManyToManyField(through='api.PackageMatrixCompany', to='api.Company'),
        ),
    ]
