# Generated by Django 3.1.4 on 2021-05-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_packagematrix_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageactivity',
            name='files',
            field=models.ManyToManyField(to='api.Media'),
        ),
    ]
