# Generated by Django 3.1.4 on 2021-06-11 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_packageactivity_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subcontractor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtask', to=settings.AUTH_USER_MODEL),
        ),
    ]
