# Generated by Django 3.1.4 on 2021-06-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20210611_0716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='editmode',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='locationmatrixpackage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='offlinemode',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='packageactivity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='packageactivitytask',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='packagematrix',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='packagematrixcompany',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='packagematrixhiddenactivitytask',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='projectnews',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectuser',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='qualityissueupdate',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='subtaskupdate',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='taskupdate',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
