# Generated by Django 3.2.4 on 2021-06-23 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_auto_20210618_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company'),
        ),
    ]
