# Generated by Django 3.2.4 on 2021-06-23 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_subtask_company'),
    ]

    operations = [
        migrations.RunSQL('''
            UPDATE subtasks SET company_id = u.company_id FROM auth_user u WHERE subcontractor_id = u.id
        ''')
    ]
