# Generated by Django 3.2.4 on 2021-06-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_migrate_subtask_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='subcontractor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_old',
        ),
    ]
