# Generated by Django 3.2.4 on 2021-06-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20210623_0600'),
    ]

    operations = [
        migrations.RunSQL("""
            UPDATE subtasks_updates
             SET old_data = jsonb_set(old_data #- '{subcontractor}', '{company}', 'null')
             WHERE old_data ? 'subcontractor' AND old_data ->> 'subcontractor' IS NULL
        """),
        migrations.RunSQL("""
            UPDATE subtasks_updates
             SET new_data = jsonb_set(new_data #- '{subcontractor}', '{company}', 'null')
             WHERE new_data ? 'subcontractor' AND new_data ->> 'subcontractor' IS NULL
        """),
        migrations.RunSQL("""
            UPDATE subtasks_updates
             SET new_data = jsonb_set(new_data #- '{subcontractor}', '{company}', u.company_id::char::jsonb)
             FROM auth_user u 
             WHERE new_data ? 'subcontractor' AND new_data ->> 'subcontractor' ~ '^\d'
               AND (new_data ->> 'subcontractor')::int = u.id
        """),
        migrations.RunSQL("""
            UPDATE subtasks_updates
             SET old_data = jsonb_set(old_data #- '{subcontractor}', '{company}', u.company_id::char::jsonb)
             FROM auth_user u 
             WHERE old_data ? 'subcontractor' AND old_data ->> 'subcontractor' ~ '^\d'
               AND (old_data ->> 'subcontractor')::int = u.id  
        """),
    ]
