# Generated by Django 3.2.4 on 2021-07-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_replace_subcontractor_to_company_in_subtask_updates'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offlinemode',
            name='offline_mode_uniqueness',
        ),
    ]
