# Generated by Django 3.2.4 on 2021-07-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_remove_offlinemode_offline_mode_uniqueness'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfflineMode',
        ),
    ]
