# Generated by Django 3.2.4 on 2021-07-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_delete_offlinemode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(choices=[('task', 'Task'), ('subtask', 'Subtask'), ('quality_issue', 'Quality Issue')], max_length=255)),
                ('generated_at', models.DateTimeField()),
                ('is_generating', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('type', models.CharField(choices=[('csv', 'Csv'), ('pdf', 'Pdf')], max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('project', 'entity', 'type'), name='reports_uniqueness'),
        ),
    ]
