# Generated by Django 3.2.4 on 2021-08-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='local_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
