# Generated by Django 3.2.4 on 2021-08-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_media_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='location_description',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
