# Generated by Django 3.2.4 on 2021-08-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_subtask_location_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='location_description',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
