# Generated by Django 3.2.4 on 2021-08-23 06:46

from django.db import migrations

from api.models import Event


def clear_events(self, *args, **kwargs):
    Event.objects().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20210820_0646'),
    ]

    operations = [
        migrations.RunPython(clear_events),
    ]
