# Generated by Django 3.2.4 on 2021-08-24 07:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_clear_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHandoverDocumentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'package_handover_document_groups',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
