# Generated by Django 3.2.4 on 2021-08-24 07:46
from django.db import migrations

from api.models import PackageHandoverDocumentGroup


def add_package_handover_document_groups(*args, **kwargs):
    PackageHandoverDocumentGroup.objects.get_or_create(name='Subcontractor Documents')
    PackageHandoverDocumentGroup.objects.get_or_create(name='Consultant Documents')
    PackageHandoverDocumentGroup.objects.get_or_create(name='H&S Consultant Documents')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_packagehandoverdocumentgroup'),
    ]

    operations = [
        migrations.RunPython(add_package_handover_document_groups)
    ]
