# Generated by Django 3.2.4 on 2021-08-25 11:46

from django.db import migrations, models
import django.db.models.deletion

from api.models import PackageHandoverDocumentType


def add_package_handover_document_type(*args, **kwargs):
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='Manufactures Literature')
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='Operating Procedures')
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='Materials Disposal')
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='Warranties & Guarantees')
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='Spares')
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='Technical Data Submission')
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='Certificates')
    PackageHandoverDocumentType.objects.get_or_create(group_id=1, name='AsBuilt (non-asset)')
    PackageHandoverDocumentType.objects.get_or_create(group_id=2, name='Compliance Statement')
    PackageHandoverDocumentType.objects.get_or_create(group_id=2, name='Strategies & Reports')
    PackageHandoverDocumentType.objects.get_or_create(group_id=2, name='Specifications')
    PackageHandoverDocumentType.objects.get_or_create(group_id=2, name='User Guides')
    PackageHandoverDocumentType.objects.get_or_create(group_id=2, name='FM Training')
    PackageHandoverDocumentType.objects.get_or_create(group_id=2, name='Planning Consents')
    PackageHandoverDocumentType.objects.get_or_create(group_id=2, name='Record Drawings')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Project Information')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Residual Risks')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Key Structural Principles')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Hazardous Materials')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Removal/Dismantling of Installed Plant and Equipment')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Equip Provided for Cleaning/Maintaining the Structure')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Nature, Location and Markings of Significant Services')
    PackageHandoverDocumentType.objects.get_or_create(group_id=3, name='Information/As-Built Drawings of Structure/Plant & Equip')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_packagehandoverdocumenttype'),
    ]

    operations = [
        migrations.RunPython(add_package_handover_document_type)
    ]
