# Generated by Django 3.2.4 on 2021-08-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_add_packagehandoverdocumenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityissueupdate',
            name='local_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtaskupdate',
            name='local_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='local_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
