# Generated by Django 3.2.4 on 2021-08-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_auto_20210827_0603'),
        ('api', '0129_packagehandover'),
    ]

    operations = [
    ]
