# Generated by Django 3.2.4 on 2021-08-31 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_merge_0129_auto_20210827_0603_0129_packagehandover'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHandoverDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_required_files', models.PositiveIntegerField(default=0)),
                ('package_handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagehandover')),
                ('package_handover_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagehandoverdocumenttype')),
            ],
            options={
                'db_table': 'package_handover_documents',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
