# Generated by Django 3.2.4 on 2021-09-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_packagehandoverdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHandoverDocumentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.media')),
                ('package_handover_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packagehandoverdocument')),
            ],
            options={
                'db_table': 'package_handover_document_medias',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
