# Generated by Django 3.2.4 on 2021-09-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0132_packagehandoverdocumentmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='snapshot',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_project', to='api.media'),
        ),
    ]
