# Generated by Django 3.2.4 on 2021-09-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_project_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSnapshotMediaThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_snapshot_thumbnail', to='api.media')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.media')),
            ],
            options={
                'db_table': 'project_snapshot_media_thumbnail',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='media',
            name='project_snapshot_thumbnails',
            field=models.ManyToManyField(related_name='_api_media_project_snapshot_thumbnails_+', through='api.ProjectSnapshotMediaThumbnail', to='api.Media'),
        ),
        migrations.AddConstraint(
            model_name='projectsnapshotmediathumbnail',
            constraint=models.UniqueConstraint(fields=('original_media', 'thumbnail'), name='api_project_snap_media_thumbnail_uniqueness'),
        ),
    ]
