# Generated by Django 3.2.4 on 2021-09-14 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20210911_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='project_snapshot_thumbnails',
        ),
        migrations.AlterField(
            model_name='projectsnapshotmediathumbnail',
            name='original_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.media'),
        ),
        migrations.AlterField(
            model_name='projectsnapshotmediathumbnail',
            name='thumbnail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_thumbnail', to='api.media'),
        ),
    ]
