# Generated by Django 3.2.4 on 2021-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_auto_20210914_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehandover',
            name='inspection_period',
            field=models.IntegerField(choices=[(None, 'Undefined'), (1, 'One'), (3, 'Three'), (6, 'Six'), (12, 'Twelve'), (18, 'Eighteen')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='packagehandover',
            name='maintenance_period',
            field=models.IntegerField(choices=[(None, 'Undefined'), (1, 'One'), (3, 'Three'), (6, 'Six'), (12, 'Twelve'), (18, 'Eighteen')], default=None, null=True),
        ),
    ]
