# Generated by Django 3.2.4 on 2021-09-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_auto_20210918_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehandoverdocumentmedia',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('contested', 'Contested'), ('requesting_approval', 'Requesting approval'), ('requested_approval_rejected', 'Requested approval rejected'), ('accepted', 'Accepted')], default='in_progress', max_length=255),
        ),
    ]
