# Generated by Django 3.1.4 on 2021-01-19 13:09
import pendulum
from django.db import connection, migrations

def get_package_matrices_without_package_handovers(cursor):
    cursor.execute("SELECT * FROM package_matrix "
                   "LEFT JOIN package_handovers ON package_matrix.id = package_handovers.package_matrix_id "
                   "WHERE package_handovers.id IS NULL AND package_matrix.deleted IS NUll;")

    return cursor.fetchall()

def create_package_handovers(*args, **kwargs):
    with connection.cursor() as cursor:
        package_matrices = get_package_matrices_without_package_handovers(cursor)

        for package_matrix in package_matrices:
            cursor.execute('INSERT INTO package_handovers (package_matrix_id, created_at, updated_at) VALUES (%s, %s, %s)', [package_matrix[0], pendulum.now(), pendulum.now()])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_packagehandoverdocumentmediaupdate'),
    ]

    operations = [
        migrations.RunPython(create_package_handovers),
    ]
