# Generated by Django 3.2.4 on 2021-10-01 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_auto_20210930_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityissue',
            name='response_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsecategory'),
        ),
        migrations.AlterField(
            model_name='responsecategory',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
