# Generated by Django 3.2.4 on 2021-10-15 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0141_auto_20211001_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehandoverdocumentmedia',
            name='last_confirmed_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packagehandoverdocumentmediaupdate'),
        ),
    ]
