# Generated by Django 3.2.4 on 2021-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_packagehandoverdocumentmedia_last_confirmed_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehandoverdocumentmedia',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('contested', 'Contested'), ('requesting_approval', 'Requesting approval'), ('requested_approval_rejected', 'Requested approval rejected'), ('accepted', 'Accepted'), ('removed', 'Removed')], default='in_progress', max_length=255),
        ),
    ]
