# Generated by Django 3.2.4 on 2021-11-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0145_add_information_field_for_package_handover_document_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehandoverdocumentmedia',
            name='uid',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
