# Generated by Django 3.2.4 on 2021-11-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_alter_packagehandoverdocumentmedia_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehandoverdocumentmedia',
            name='uid',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='packagehandoverdocumentmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('uid',), name='package_handover_document_media_unique_uid'),
        ),
    ]
