# Generated by Django 3.2.4 on 2021-11-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_auto_20211105_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHandoverDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asset_handover_document_types',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='assethandoverdocumenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('name',), name='asset_handover_document_type_unique'),
        ),
    ]
