# Generated by Django 3.2.4 on 2021-11-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_add_asset_handover_document_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHandover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.locationmatrix')),
                ('package_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packageactivity')),
            ],
            options={
                'db_table': 'asset_handovers',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='assethandover',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('package_activity', 'location_matrix'), name='asset_handover_unique'),
        ),
    ]
