# Generated by Django 3.2.4 on 2021-11-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0151_auto_20211112_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHandoverDocumentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_handover_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assethandoverdocument')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.media')),
            ],
            options={
                'db_table': 'asset_handover_document_media',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='assethandoverdocumentmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('asset_handover_document', 'media'), name='asset_handover_document_media_unique'),
        ),
    ]
