# Generated by Django 3.2.4 on 2021-11-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0152_auto_20211115_0625'),
        ('api', '0152_auto_20211116_0647'),
    ]

    operations = [
    ]
