# Generated by Django 3.2.4 on 2021-11-29 12:32

from django.db import migrations

from api.models import PackageHandoverDocumentType, PackageHandoverDocumentGroup


def add_package_handover_document_types(*args, **kwargs):
    group = PackageHandoverDocumentGroup.objects.filter(name='Multiplex Documents').get()
    PackageHandoverDocumentType.objects.get_or_create(name='Practical Completion Checklist', group_id=group.pk)
    PackageHandoverDocumentType.objects.get_or_create(name='Statutory Authorities', group_id=group.pk)
    PackageHandoverDocumentType.objects.get_or_create(name='Master Schedules', group_id=group.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_add_multiplex_documents_group_20211129_1231'),
    ]

    operations = [
        migrations.RunPython(add_package_handover_document_types),
    ]
