# Generated by Django 3.2.4 on 2021-11-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0156_add_subcontractor_20211129_1455'),
        ('api', '0157_add_multiplex_documents_types_20211129_1232'),
    ]

    operations = [
    ]
