# Generated by Django 3.2.4 on 2021-12-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_assethandoverdocumentmedia_status'),
        ('api', '0158_merge_20211129_0916'),
    ]

    operations = [
    ]
