# Generated by Django 3.2.4 on 2021-11-29 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0158_assethandoverdocumentmedia_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHandoverDocumentMediaUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('old_data', models.JSONField()),
                ('new_data', models.JSONField()),
                ('asset_handover_document_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assethandoverdocumentmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_handover_document_media_updates',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
