# Generated by Django 3.2.4 on 2021-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_assethandoverdocumentmediaupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethandoverdocumentmedia',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('contested', 'Contested'), ('in_progress', 'In Progress'), ('removed', 'Removed'), ('requested_approval_rejected', 'Requested Approval Rejected'), ('requesting_approval', 'Requesting Approval')], max_length=255),
        ),
    ]
