# Generated by Django 3.2.4 on 2021-12-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0159_assethandoverdocumentmediaupdate'),
        ('api', '0159_merge_20211201_0852'),
    ]

    operations = [
    ]
