# Generated by Django 3.2.4 on 2021-12-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0160_merge_20211201_1023'),
        ('api', '0161_change_deletion_strategy_for_last_confirmed_update_20211201_0616'),
    ]

    operations = [
    ]
