# Generated by Django 3.2.4 on 2021-12-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0162_merge_20211203_0654'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packagehandoverdocumentmedia',
            table='package_handover_document_media',
        ),
    ]
