# Generated by Django 3.2.4 on 2021-12-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0163_add_h_s_documents_types_20211129_1232'),
        ('api', '0163_alter_packagehandoverdocumentmedia_table'),
    ]

    operations = [
    ]
