# Generated by Django 3.2.4 on 2022-01-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0165_assethandoverdocumentmedia_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethandoverinformation',
            name='asset_handover',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.assethandover'),
        ),
    ]
