# Generated by Django 3.2.4 on 2022-01-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0166_auto_20220113_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_subtask_visible_for_clients',
            field=models.BooleanField(default=False),
        ),
    ]
