# Generated by Django 3.2.4 on 2022-02-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0167_project_is_subtask_visible_for_clients'),
        ('api', '0168_initial_fill_asset_handover_statistics_table_20220126_1932'),
    ]

    operations = [
    ]
