# Generated by Django 3.2.4 on 2022-02-12 04:54

from django.db import migrations, models, connection
import django.db.models.deletion

def fill_last_update_id_for_existing_subtasks(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            update subtasks
            set last_update_id = data_table.last_update_id
            from (
                select unnest(
                    (SELECT ARRAY(SELECT subtasks.id
                        FROM subtasks
                             LEFT JOIN LATERAL (
                                SELECT *
                                FROM subtasks_updates
                                WHERE subtasks.id = subtasks_updates.subtask_id
                                ORDER BY subtasks_updates."created_at" DESC
                                LIMIT 1
                            ) subtasks_updates ON TRUE
                    ))
                ) as id,
                 unnest((SELECT ARRAY(
                    SELECT subtasks_updates.id
                    FROM subtasks
                             LEFT JOIN LATERAL (
                        SELECT *
                        FROM subtasks_updates
                        WHERE subtasks.id = subtasks_updates.subtask_id
                        ORDER BY subtasks_updates."created_at" DESC
                        LIMIT 1
                        ) subtasks_updates ON TRUE
                ))) as last_update_id) as data_table
            where subtasks.id = data_table.id;
        """)

def reverse_function(*args, **kwargs):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0170_add_missing_package_handovers_20220202_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='last_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_subtask_update', to='api.subtaskupdate'),
        ),
        migrations.RunPython(code=fill_last_update_id_for_existing_subtasks, reverse_code=reverse_function)
    ]
