# Generated by Django 3.2.4 on 2022-02-12 07:09

from django.db import migrations, models, connection
import django.db.models.deletion

def fill_project_id_for_existing_tasks(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            update tasks
            set project_id = data_table.project_id
            from (
                     select unnest(
                                    (SELECT ARRAY(
                                                    SELECT tasks.id
                                                    FROM tasks
                                                             INNER JOIN location_matrix ON tasks.location_matrix_id = location_matrix.id
                                                ))
                                )                  as id,
                            unnest((SELECT ARRAY(
                                                   SELECT location_matrix.project_id
                                                   FROM tasks
                                                            INNER JOIN location_matrix ON tasks.location_matrix_id = location_matrix.id
                                               ))) as project_id) as data_table
            where tasks.id = data_table.id;
        """)

def reverse_function(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0171_add_last_update_to_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.RunPython(code=fill_project_id_for_existing_tasks, reverse_code=reverse_function)
    ]
