# Generated by Django 3.2.4 on 2022-02-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0173_user_group'),
    ]
    sql_code = """
        UPDATE auth_user
        SET group_id = data_table.group_id
        FROM (
            SELECT unnest((SELECT ARRAY(SELECT au.id FROM auth_user au LEFT JOIN LATERAL (SELECT * FROM auth_user_groups aug WHERE au.id = aug.user_id ORDER BY aug.id DESC LIMIT 1) aug ON TRUE))) AS user_id,
            unnest((SELECT ARRAY(SELECT aug.group_id FROM auth_user au LEFT JOIN LATERAL (SELECT * FROM auth_user_groups aug WHERE au.id = aug.user_id ORDER BY aug.id DESC LIMIT 1) aug ON TRUE))) AS group_id
        ) AS data_table
        WHERE auth_user.id = data_table.user_id;
    """
    operations = [
        migrations.RunSQL(sql=sql_code, reverse_sql="UPDATE auth_user SET group_id = NULL;" ),
    ]
