# Generated by Django 3.2.4 on 2022-02-10 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0179_initial_fill_asset_handover_statistics_table_for_project_20220301_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('document_type', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.media')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package')),
                ('package_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.packageactivity')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('building', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('information', models.TextField(null=True, blank=True)),
                ('uid', models.CharField(max_length=255, null=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'db_table': 'handover_documents',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
