# Generated by Django 3.2.4 on 2022-03-30 08:44

from django.db import migrations, models
import django.db.models.deletion


def get_sql(*args, **kwargs):
    return """
        UPDATE asset_handovers ah SET project_id = lm.project_id FROM location_matrix lm WHERE ah.location_matrix_id = lm.id; 
    """


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0182_fill_handover_documents_from_package_handover_document_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethandover',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.RunSQL(sql=get_sql(), reverse_sql="UPDATE asset_handovers SET project_id=NULL;")
    ]
