# Generated by Django 3.2.4 on 2022-04-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0184_assethandover_asset_handovers_ihe6oz_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageHandoverStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('required_files_count', models.IntegerField(default=0)),
                ('uploaded_files_count', models.IntegerField(default=0)),
                ('statistics_by_statuses', models.JSONField(default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'package_handover_statistics',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
