# Generated by Django 3.2.4 on 2022-04-11 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0186_initial_fill_package_handover_statistics_table_for_package_handover_documents_20220405_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehandoverdocument',
            name='package_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packageactivity'),
        ),
        migrations.AddField(
            model_name='packagehandoverdocument',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
