# Generated by Django 3.2.4 on 2022-04-11 06:17

from django.db import migrations, connection


def clear_project_and_package_activity(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE package_handover_document SET project_id=NULL, package_activity_id=NULL;
        """)


def fill_project_and_package_activity(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE package_handover_documents phm SET project_id=pm.project_id, package_activity_id=pm.package_activity_id 
              FROM package_handovers ph INNER JOIN package_matrix pm ON pm.id = ph.package_matrix_id
              WHERE phm.package_handover_id = ph.id
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_add_project_and_package_activity_fields_to_package_handover_documents_20220411_0616'),
    ]

    operations = [
        migrations.RunPython(code=fill_project_and_package_activity, reverse_code=clear_project_and_package_activity)
    ]
