# Generated by Django 3.2.4 on 2022-04-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0189_auto_20220411_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagehandoverstatistics',
            name='required_files_count',
        ),
        migrations.RemoveField(
            model_name='packagehandoverstatistics',
            name='uploaded_files_count',
        ),
        migrations.AddField(
            model_name='packagehandoverstatistics',
            name='accepted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagehandoverstatistics',
            name='contested_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagehandoverstatistics',
            name='in_progress_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagehandoverstatistics',
            name='package_handover_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packagehandoverdocument'),
        ),
        migrations.AddField(
            model_name='packagehandoverstatistics',
            name='removed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagehandoverstatistics',
            name='requested_approval_rejected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packagehandoverstatistics',
            name='requesting_approval_count',
            field=models.IntegerField(default=0),
        ),
    ]
