# Generated by Django 3.2.4 on 2022-04-11 08:41
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, connection

from api.models import PackageHandoverDocument


def clear_package_handover_content_type(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE package_handover_statistics SET package_handover_document_id=NULL;
        """)


def fill_package_handover_document(*args, **kwargs):
    with connection.cursor() as cursor:
        package_handover_document_content_type = ContentType.objects.get_for_model(PackageHandoverDocument).id

        cursor.execute("""
            UPDATE package_handover_statistics
            SET package_handover_document_id=object_id
            WHERE content_type_id=%s;
        """, (package_handover_document_content_type,))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_migrate_package_handover_statistics_by_statuses'),
    ]

    operations = [
        migrations.RunPython(code=fill_package_handover_document, reverse_code=clear_package_handover_content_type)
    ]
