# Generated by Django 3.2.4 on 2022-04-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_fill_package_handover_document_in_package_handover_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagehandoverstatistics',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='packagehandoverstatistics',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='packagehandoverstatistics',
            name='statistics_by_statuses',
        ),
    ]
