# Generated by Django 3.2.4 on 2022-04-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_remove_polymorphic_relationship_from_package_handover_statistics_20220411_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethandoverstatistics',
            name='accepted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assethandoverstatistics',
            name='contested_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assethandoverstatistics',
            name='in_progress_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assethandoverstatistics',
            name='removed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assethandoverstatistics',
            name='requested_approval_rejected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assethandoverstatistics',
            name='requesting_approval_count',
            field=models.IntegerField(default=0),
        ),
    ]
