# Generated by Django 3.2.4 on 2022-04-13 11:28

from django.db import migrations, connection


def migrate_statistics_by_statuses(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE asset_handover_statistics
            SET in_progress_count=CASE
                                      WHEN cast(statistics_by_statuses ->> 'in_progress' AS TEXT) IS NULL THEN 0
                                      ELSE (statistics_by_statuses ->> 'in_progress')::int
                END,
                contested_count=CASE
                                    WHEN cast(statistics_by_statuses ->> 'contested' AS TEXT) IS NULL THEN 0
                                    ELSE (statistics_by_statuses ->> 'contested')::int
                    END,
                removed_count=CASE
                                  WHEN cast(statistics_by_statuses ->> 'removed' AS TEXT) IS NULL THEN 0
                                  ELSE (statistics_by_statuses ->> 'removed')::int
                    END,
                accepted_count=CASE
                                   WHEN cast(statistics_by_statuses ->> 'accepted' AS TEXT) IS NULL THEN 0
                                   ELSE (statistics_by_statuses ->> 'accepted')::int
                    END,
                requesting_approval_count=CASE
                                              WHEN cast(statistics_by_statuses ->> 'requesting_approval' AS TEXT) IS NULL THEN 0
                                              ELSE (statistics_by_statuses ->> 'requesting_approval')::int
                    END,
                requested_approval_rejected_count=CASE
                                                      WHEN cast(statistics_by_statuses ->> 'requested_approval_rejected' AS TEXT) IS NULL THEN 0
                                                      ELSE (statistics_by_statuses ->> 'requested_approval_rejected')::int
                    END;
        """)


def revert_changes(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE asset_handover_statistics SET in_progress_count=0, accepted_count=0, contested_count=0, removed_count=0, requesting_approval=0, requested_approal_rejected=0;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_create_different_columns_for_asset_handover_statistics_by_statuses_20220413_1124'),
    ]

    operations = [
        migrations.RunPython(code=migrate_statistics_by_statuses, reverse_code=revert_changes)
    ]
