# Generated by Django 3.2.4 on 2022-04-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_migrate_asset_handover_statistics_by_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethandoverstatistics',
            name='statistics_by_statuses',
        ),
    ]
