# Generated by Django 3.2.4 on 2022-04-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_remove_assethandoverstatistics_statistics_by_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethandoverstatistics',
            name='asset_handover_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.assethandoverdocument'),
        ),
    ]
