# Generated by Django 3.2.4 on 2022-04-13 11:52
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, connection

from api.models import AssetHandoverDocument


def clear_package_handover_content_type(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE asset_handover_statistics SET asset_handover_document_id=NULL;
        """)


def fill_asset_handover_document(*args, **kwargs):
    with connection.cursor() as cursor:
        asset_handover_document_content_type = ContentType.objects.get_for_model(AssetHandoverDocument).id

        cursor.execute("""
            UPDATE asset_handover_statistics
            SET asset_handover_document_id=object_id
            WHERE content_type_id=%s;
        """, (asset_handover_document_content_type,))

        cursor.execute("""
            DELETE from asset_handover_statistics WHERE asset_handover_document_id IS NULL;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_assethandoverstatistics_asset_handover_document'),
    ]

    operations = [
        migrations.RunPython(code=fill_asset_handover_document, reverse_code=clear_package_handover_content_type)
    ]
