# Generated by Django 3.2.4 on 2022-04-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0198_fill_asset_handover_statistics_reference_to_asset_handover_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethandoverstatistics',
            name='asset_handover_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assethandoverdocument'),
        ),
    ]
