# Generated by Django 3.2.4 on 2022-04-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0199_alter_assethandoverstatistics_asset_handover_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethandoverstatistics',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='assethandoverstatistics',
            name='object_id',
        ),
    ]
