# Generated by Django 3.2.4 on 2022-04-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0200_remove_polymorphic_relationship_from_asset_handover_statistics_20220413_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assethandoverstatistics',
            name='filled_information_count',
        ),
        migrations.RemoveField(
            model_name='assethandoverstatistics',
            name='total_information_count',
        ),
        migrations.RemoveField(
            model_name='assethandoverstatistics',
            name='uploaded_files_count',
        ),
    ]
