# Generated by Django 3.2.4 on 2022-04-26 11:02

from django.db import migrations, connection


def delete_asset_handovers(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            DELETE
            FROM asset_handover_statistics ahs
                USING asset_handover_documents ahd
            WHERE ahs.asset_handover_document_id = ahd.id
              AND number_required_files = 0
              AND ahd.asset_handover_id = ANY (SELECT delete_candidate_query.asset_handover_id
                                               FROM (SELECT bool_and(aggregating_query.without_media) is_delete_candidate,
                                                            asset_handover_id
                                                     FROM (SELECT DISTINCT ON (distinct_query.id) distinct_query.id,
                                                                                                  asset_handover_id,
                                                                                                  (document_media.id IS NULL) without_media
                                                           FROM asset_handover_documents distinct_query
                                                                    LEFT JOIN asset_handover_document_media document_media
                                                                              ON distinct_query.id = document_media.asset_handover_document_id) aggregating_query
                                                     GROUP BY aggregating_query.asset_handover_id) delete_candidate_query
                                               WHERE is_delete_candidate);
        """)

        cursor.execute("""
            DELETE
            FROM asset_handover_information ahi
                USING asset_handovers ah
            WHERE ahi.asset_handover_id = ah.id
              AND ah.id = ANY (SELECT delete_candidate_query.asset_handover_id
                                               FROM (SELECT bool_and(aggregating_query.without_media) is_delete_candidate,
                                                            asset_handover_id
                                                     FROM (SELECT DISTINCT ON (distinct_query.id) distinct_query.id,
                                                                                                  asset_handover_id,
                                                                                                  (document_media.id IS NULL) without_media
                                                           FROM asset_handover_documents distinct_query
                                                                    LEFT JOIN asset_handover_document_media document_media
                                                                              ON distinct_query.id = document_media.asset_handover_document_id) aggregating_query
                                                     GROUP BY aggregating_query.asset_handover_id) delete_candidate_query
                                               WHERE is_delete_candidate);
        """)

        cursor.execute("""
            DELETE
            FROM asset_handover_documents ahd
            WHERE number_required_files = 0
              AND ahd.asset_handover_id = ANY (SELECT delete_candidate_query.asset_handover_id
                                               FROM (SELECT bool_and(aggregating_query.without_media) is_delete_candidate,
                                                            asset_handover_id
                                                     FROM (SELECT DISTINCT ON (distinct_query.id) distinct_query.id,
                                                                                                  asset_handover_id,
                                                                                                  (document_media.id IS NULL) without_media
                                                           FROM asset_handover_documents distinct_query
                                                                    LEFT JOIN asset_handover_document_media document_media
                                                                              ON distinct_query.id = document_media.asset_handover_document_id) aggregating_query
                                                     GROUP BY aggregating_query.asset_handover_id) delete_candidate_query
                                               WHERE is_delete_candidate);
        """)

        cursor.execute("""
            DELETE
            FROM asset_handovers ah
            WHERE NOT exists(SELECT (1) FROM asset_handover_documents ahd WHERE ahd.asset_handover_id = ah.id);
        """)


def revert_changes(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0201_auto_20220413_1301'),
    ]

    operations = [
        migrations.RunPython(code=delete_asset_handovers, reverse_code=revert_changes)
    ]
