# Generated by Django 3.2.4 on 2022-05-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0202_remove_asset_handovers_without_required_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethandoverstatistics',
            name='asset_handover_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.assethandoverdocument'),
        ),
        migrations.AlterField(
            model_name='handoverdocument',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoverdocument',
            name='building',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='handoverdocument',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
