# Generated by Django 3.2.4 on 2022-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0204_refill_handover_documents_from_package_handover_document_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handoverdocument',
            old_name='object_id',
            new_name='entity_id',
        ),
        migrations.AddField(
            model_name='handoverdocument',
            name='entity',
            field=models.CharField(choices=[('asset_handover', 'Asset handover'), ('package_handover', 'Package handover')], max_length=255, null=True),
        ),
    ]
