# Generated by Django 3.2.4 on 2022-05-23 13:56
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, connection

from api.models import AssetHandoverDocumentMedia, PackageHandoverDocumentMedia, HandoverDocument


def migrate_content_type(*args, **kwargs):
    with connection.cursor() as cursor:
        asset_handover_document_media_content_type = ContentType.objects.get_for_model(AssetHandoverDocumentMedia).id
        package_handover_document_media_content_type = ContentType.objects.get_for_model(PackageHandoverDocumentMedia).id
        cursor.execute("""
            UPDATE handover_documents SET entity=CASE WHEN content_type_id=%s THEN %s WHEN content_type_id=%s THEN %s END;
        """, (asset_handover_document_media_content_type, HandoverDocument.Entities.ASSET_HANDOVER.value,
              package_handover_document_media_content_type, HandoverDocument.Entities.PACKAGE_HANDOVER.value))


def reverse_migration(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE handover_documents SET entity=null;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0205_handover_document_add_entity_fields_20220523_1354'),
    ]

    operations = [
        migrations.RunPython(code=migrate_content_type, reverse_code=reverse_migration)
    ]
