# Generated by Django 3.2.4 on 2022-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0206_handover_document_migrate_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handoverdocument',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='handoverdocument',
            name='entity',
            field=models.CharField(choices=[('asset_handover', 'Asset handover'), ('package_handover', 'Package handover')], max_length=255),
        ),
    ]
