# Generated by Django 3.2.4 on 2022-06-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0207_remove_handoverdocument_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverdocument',
            name='entity',
            field=models.CharField(choices=[('asset_handover', 'Asset handover'), ('package_handover', 'Package handover')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
