# Generated by Django 3.2.4 on 2022-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0211_auto_20220705_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_quality_report_visible_for_clients',
            field=models.BooleanField(default=True),
        ),
    ]
