# Generated by Django 3.2.4 on 2022-07-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0212_project_is_quality_report_visible_for_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_quality_report_visible_for_clients',
            new_name='is_task_visible_for_clients',
        ),
    ]
