# Generated by Django 3.2.4 on 2022-08-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0213_rename_is_quality_report_visible_for_clients_project_is_task_visible_for_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disable_user_registration_from_mobile_devices', models.BooleanField(default=False, verbose_name='Disable user registration from mobile devices')),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
    ]
