# Generated by Django 3.2.15 on 2022-10-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0215_add_is_comment_field_20220824_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsnapshotmediathumbnail',
            name='for_project_snapshot',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
