# Generated by Django 3.2.15 on 2022-10-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0216_projectsnapshotmediathumbnail_for_project_snapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectsnapshotmediathumbnail',
            name='api_project_snap_media_thumbnail_uniqueness',
        ),
        migrations.AlterModelTable(
            name='projectsnapshotmediathumbnail',
            table='media_thumbnails',
        ),
    ]
