# Generated by Django 3.2.15 on 2022-10-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0217_remove_constraint_and_rename_table_20221021_0532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectSnapshotMediaThumbnail',
            new_name='MediaThumbnail',
        ),
        migrations.AlterModelTable('MediaThumbnail', 'media_thumbnails')
    ]
