# Generated by Django 3.2.15 on 2022-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0219_add_media_thumbnails_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediathumbnail',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mediathumbnail',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
