# Generated by Django 3.2.15 on 2022-11-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0221_remove_media_thumbnails'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO media_thumbnails(original_media_id, thumbnail_id, created_at, updated_at)
                SELECT id, id, now(), now() FROM media WHERE right(name, 3) IN ('jpg', 'png', 'bmp') OR right(name, 4) IN ('jpeg', 'jfif');
            """,
            reverse_sql="""
                DELETE FROM media_thumbnails WHERE original_media_id = thumbnail_id;
            """)
    ]
