# Generated by Django 3.2.15 on 2022-11-22 12:47
from django.core.management import call_command
from django.db import migrations


def clear_duplicated_subtasks(*args, **kwargs):
    call_command('clear_duplicated_subtasks_by_quality_issue')


def reverse_code(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0222_fill_media_thumbnails_for_images_20221114_1442'),
    ]

    operations = [
        migrations.RunPython(code=clear_duplicated_subtasks, reverse_code=reverse_code),
    ]
