# Generated by Django 3.2.15 on 2022-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_remove_duplicated_by_quality_issue_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethandoverinformation',
            name='guid_external_ref',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assethandoverinformation',
            name='manufacture_serial_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assethandoverinformation',
            name='model_number',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assethandoverinformation',
            name='warranty',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
