# Generated by Django 3.2.15 on 2022-12-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0223_remove_duplicated_by_quality_issue_subtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'asset_registers',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='assetregister',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('project',), name='asset_register_uniqueness'),
        ),
    ]
