# Generated by Django 3.2.15 on 2022-12-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0224_asset_register_create_20221209_1830'),
        ('api', '0224_auto_20221208_1914'),
    ]

    operations = [
    ]
