# Generated by Django 3.2.15 on 2022-12-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0225_merge_20221213_0905'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                INSERT INTO asset_registers(deleted, created_at, updated_at, data, project_id)
                SELECT null, now(), now(), '{}', id FROM projects;
            """,
            reverse_sql="TRUNCATE asset_registers;")
    ]
