# Generated by Django 3.2.15 on 2022-12-15 20:42
from django.db import migrations, models, connection


def clear_old_file_plans(*args, **kwargs):
    with connection.cursor() as cursor:
        cursor.execute("""
            DELETE
            FROM floor_plans
            WHERE id NOT IN (SELECT max(id)
                             FROM floor_plans
                             GROUP BY project_id, package_id, building, level)
        """)


def reverse_code(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0227_remove_users_company_admin_from_projects'),
    ]

    operations = [
        migrations.RunPython(code=clear_old_file_plans, reverse_code=reverse_code),
        migrations.RemoveConstraint(
            model_name='floorplan',
            name='floor_plans_uniqueness',
        ),
        migrations.AddConstraint(
            model_name='floorplan',
            constraint=models.UniqueConstraint(fields=('project', 'package', 'building', 'level'), name='floor_plans_unique_media'),
        ),
    ]
