# Generated by Django 3.2.15 on 2022-12-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0228_auto_20221215_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polygon', models.JSONField()),
                ('area', models.CharField(max_length=255)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floorplan')),
            ],
            options={
                'db_table': 'floor_plan_areas',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='floorplanarea',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('floor_plan', 'area'), name='floor_plan_areas_uniqueness'),
        ),
    ]
