# Generated by Django 3.2.15 on 2022-12-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0229_create_floor_plan_area_20221228_1528'),
        ('api', '0229_subtaskupdatecounter'),
    ]

    operations = [
    ]
