# Generated by Django 3.2.15 on 2023-01-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0230_floorplanimage'),
        ('api', '0230_merge_20230901_1610'),
    ]

    operations = [
    ]
