# Generated by Django 3.2.15 on 2023-01-18 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0231_merge_0230_floorplanimage_0230_merge_20230901_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanAreaPin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('pin', models.JSONField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('floor_plan_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floorplanarea')),
            ],
            options={
                'db_table': 'floor_plan_area_pins',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
