# Generated by Django 3.2.15 on 2023-02-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0232_floorplanareapin'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageactivity',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='packageactivity',
            name='description_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_activity_description_image', to='api.media'),
        ),
    ]
