# Generated by Django 3.2.15 on 2023-02-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
        ('api', '0233_add_description_package_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanRevisionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=255)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reversion.revision')),
            ],
            options={
                'db_table': 'floor_plan_revision_meta',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
