# Generated by Django 3.2.15 on 2023-02-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
        ('api', '0234_floorplanrevisionmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanRevision',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reversion.revision',),
        ),
    ]
