# Generated by Django 3.2.15 on 2023-02-27 13:57
from django.conf import settings
from django.core.management import call_command
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0235_floor_plan_revision'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda *args, **kwargs: call_command('createinitialrevisions') if not settings.IS_TEST else None,
            reverse_code=lambda *args, **kwargs: ...
        )
    ]
