# Generated by Django 3.2.15 on 2022-12-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0236_alter_packageactivity_description_image'),
        ('api', '0236_fill_initial_revisions'),
    ]

    operations = [
    ]
