# Generated by Django 3.2.15 on 2023-03-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0237_merge_20232802_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlanAreaPinThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_plan_area_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.floorplanareapin')),
                ('thumbnail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.media')),
            ],
            options={
                'db_table': 'floor_plan_area_pin_thumbnails',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
