# Generated by Django 3.2.15 on 2023-04-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_floorplanareapinthumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtask',
            name='closed_files_count',
            field=models.IntegerField(default=0),
        ),
    ]
