# Generated by Django 3.2.15 on 2023-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0238_floorplanareapinthumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanareapinthumbnail',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('area', 'Area')], max_length=255, null=True),
        ),
    ]
