# Generated by Django 3.2.15 on 2023-04-11 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_add_location_fields_to_task_20230411_0907'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE tasks
                SET building = lm.building,
                    level    = lm.level,
                    area     = lm.area
                FROM location_matrix lm
                WHERE tasks.location_matrix_id = lm.id;
            """,
            reverse_sql="""
                UPDATE tasks
                SET building = null,
                    level    = null, 
                    area     = null;
            """),
        migrations.RunSQL(
            sql="""
                UPDATE tasks
                SET package_id = pm.package_id
                FROM package_matrix pm
                WHERE tasks.project_id = pm.project_id
                  AND tasks.package_activity_id = pm.package_activity_id;
            """,
            reverse_sql="""
                UPDATE tasks
                SET package_id = null;
            """
        )
    ]
