# Generated by Django 3.2.15 on 2023-04-14 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_migrate_location_matrix_fields_to_task_20230412_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='building',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['building'], name='tasks_building_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['level'], name='tasks_level_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['area'], name='tasks_area_index'),
        ),
    ]
