# Generated by Django 3.2.15 on 2023-04-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0240_fill_subtask_files_counter_20230415_1730'),
        ('api', '0241_auto_20230414_0918'),
    ]

    operations = [
    ]
