# Generated by Django 3.2.15 on 2023-04-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0239_floorplanareapinthumbnail_type'),
        ('api', '0242_merge_20230418_0818'),
    ]

    operations = [
    ]
