# Generated by Django 3.2.15 on 2023-04-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0243_merge_20230419_0802'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                WITH t AS (SELECT floor_plan_area_pin_id,
                                  min(thumbnail_id) area,
                                  max(thumbnail_id) general
                           FROM (SELECT *, row_number() OVER (PARTITION BY floor_plan_area_pin_id ORDER BY created_at DESC ) post_p
                                 FROM floor_plan_area_pin_thumbnails WHERE deleted IS NULL) f
                           WHERE f.post_p < 3
                           GROUP BY floor_plan_area_pin_id)
                UPDATE floor_plan_area_pin_thumbnails
                SET type = CASE WHEN thumbnail_id = t.general THEN 'general' ELSE 'area' END
                FROM t
                WHERE floor_plan_area_pin_thumbnails.floor_plan_area_pin_id = t.floor_plan_area_pin_id
                  AND deleted IS NULL;
            """,
            reverse_sql="""
                UPDATE floor_plan_area_pin_thumbnails SET type = null;
            """
        )
    ]
