# Generated by Django 3.2.15 on 2023-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0244_migrate_floor_plan_area_pin_thumbnail_type_20230420_1036'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['project_id', 'status', '-deleted'], name='tasks_project_id_status_deleted'),
        ),
    ]
