# Generated by Django 3.2.15 on 2023-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0245_task_tasks_project_id_status_deleted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_building_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_level_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_area_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_project_id_status_deleted',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['building', 'id', '-deleted', 'status', 'project_id'], name='tasks_building_id_deleted_status_project_idindex'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['level', 'id', '-deleted', 'status', 'project_id'], name='tasks_level_id_deleted_status_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['area', 'id', '-deleted', 'status', 'project_id'], name='tasks_area_id_deleted_status_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['package', 'id', '-deleted', 'status', 'project_id'], name='tasks_package_id_deleted_status_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['created_at', 'id', '-deleted', 'status', 'project_id'], name='tasks_created_at_id_deleted_status_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['updated_at', 'id', '-deleted', 'status', 'project_id'], name='tasks_updated_at_id_deleted_status_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(fields=['status', 'id', '-deleted', 'status', 'project_id'], name='tasks_status_id_deleted_status_project_index'),
        ),
    ]
