# Generated by Django 3.2.15 on 2023-04-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_add_complex_indexes_20230426_1717'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_building_id_deleted_status_project_idindex',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_level_id_deleted_status_project_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_area_id_deleted_status_project_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_package_id_deleted_status_project_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_created_at_id_deleted_status_project_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_updated_at_id_deleted_status_project_index',
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='tasks_status_id_deleted_status_project_index',
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(condition=models.Q(models.Q(('status', 'not_applicable'), _negated=True), ('deleted__isnull', True)), fields=['building', 'id', 'project_id'], name='tasks_building_id_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(condition=models.Q(models.Q(('status', 'not_applicable'), _negated=True), ('deleted__isnull', True)), fields=['level', 'id', 'project_id'], name='tasks_level_id_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(condition=models.Q(models.Q(('status', 'not_applicable'), _negated=True), ('deleted__isnull', True)), fields=['area', 'id', 'project_id'], name='tasks_area_id_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(condition=models.Q(models.Q(('status', 'not_applicable'), _negated=True), ('deleted__isnull', True)), fields=['package', 'id', 'project_id'], name='tasks_package_id_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(condition=models.Q(models.Q(('status', 'not_applicable'), _negated=True), ('deleted__isnull', True)), fields=['created_at', 'id', 'project_id'], name='tasks_created_at_id_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(condition=models.Q(models.Q(('status', 'not_applicable'), _negated=True), ('deleted__isnull', True)), fields=['updated_at', 'id', 'project_id'], name='tasks_updated_at_id_project_index'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.Index(condition=models.Q(models.Q(('status', 'not_applicable'), _negated=True), ('deleted__isnull', True)), fields=['status', 'id', 'project_id'], name='tasks_status_id_project_index'),
        ),
    ]
