# Generated by Django 3.2.15 on 2023-04-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0246_add_complex_indexes_20230426_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='building',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
    ]
