# Generated by Django 3.2.15 on 2023-04-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_add_tasks_fields_to_subtask_20230428_0743'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE subtasks
                SET building=t.building,
                    level=t.level,
                    area=t.area,
                    project_id=t.project_id
                FROM tasks t
                WHERE subtasks.task_id = t.id;
            """,
            reverse_sql="""
                UPDATE subtasks
                SET building=null,
                    level=null,
                    area=null,
                    project_id=null;
            """
        ),
    ]
