# Generated by Django 3.2.15 on 2023-04-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0248_fill_subtask_fields_20230429_0910'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE subtasks
                ADD COLUMN level_number double precision GENERATED ALWAYS AS (
                    CASE
                        WHEN "level"::text ~* '(^-\d.)|(^0.)'
                            THEN CAST(regexp_replace("level", '[a-zA-Z]+', '.') || '0001' AS double precision)
                        ELSE CAST(substring("level", '^(-?\d+)') AS double precision) END
                    ) STORED;
            """,
            reverse_sql="""
                ALTER TABLE subtasks
                DROP COLUMN IF EXISTS level_number;
            """
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subtasks
                ADD COLUMN level_postfix varchar(50) GENERATED ALWAYS AS (
                    NULLIF(regexp_replace("level", '^(-?\d+)', ''), '')
                    ) STORED;
            """,
            reverse_sql="""
                ALTER TABLE subtasks
                DROP COLUMN IF EXISTS level_postfix;
            """
        )
    ]
