# Generated by Django 3.2.15 on 2023-04-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0249_add_level_parts_20230429_0917'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE subtasks
                ADD COLUMN status_weight_for_subcontractor numeric GENERATED ALWAYS AS (
                    CASE
                        WHEN "status" = 'in_progress' THEN 1
                        WHEN "status" = 'inspection_rejected' THEN 2
                        WHEN "status" = 'under_inspection' THEN 3
                        WHEN "status" = 'declined' THEN 4
                        WHEN "status" = 'requesting_approval' THEN 5
                        WHEN "status" = 'requested_approval_rejected' THEN 6
                        WHEN "status" = 'contested' THEN 7
                        WHEN "status" = 'closed' THEN 8
                        WHEN "status" = 'removed' THEN 9
                        ELSE 100 END
                    ) STORED;
            """,
            reverse_sql="""
                ALTER TABLE subtasks
                DROP COLUMN IF EXISTS status_weight_for_subcontractor;
            """
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE subtasks
                ADD COLUMN status_weight_for_staff numeric GENERATED ALWAYS AS (
                    CASE
                        WHEN "status" = 'under_inspection' THEN 1
                        WHEN "status" = 'declined' THEN 2
                        WHEN "status" = 'requested_approval_rejected' THEN 3
                        WHEN "status" = 'in_progress' THEN 4
                        WHEN "status" = 'inspection_rejected' THEN 5
                        WHEN "status" = 'requesting_approval' THEN 6
                        WHEN "status" = 'contested' THEN 7
                        WHEN "status" = 'closed' THEN 8
                        WHEN "status" = 'removed' THEN 9
                        ELSE 100 END
                    ) STORED;
            """,
            reverse_sql="""
                ALTER TABLE subtasks
                DROP COLUMN IF EXISTS status_weight_for_staff;
            """
        )
    ]
