# Generated by Django 3.2.15 on 2023-05-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0247_change_tasks_indexes_20230427_1323'),
        ('api', '0251_add_status_weight_indexes_20230429_1143'),
    ]

    operations = [
    ]
