# Generated by Django 3.2.15 on 2023-05-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0254_location_matrix_package_index_20230502_1643'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locationmatrix',
            constraint=models.Index(condition=models.Q(('deleted__isnull', True)), fields=['building', 'id'], name='location_matrix_building_id_index'),
        ),
    ]
