# Generated by Django 3.2.15 on 2023-06-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0255_locationmatrix_location_matrix_building_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_api_access_enabled',
            field=models.BooleanField(default=False),
        ),
    ]