# Generated by Django 3.2.15 on 2023-06-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0256_project_api_access_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_api_access_allowed',
            field=models.BooleanField(default=False),
        ),
    ]