# Generated by Django 3.2.15 on 2023-07-04 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0257_user_api_access_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(editable=False, unique=True)),
                ('expires_at', models.DateField()),
                ('has_access_to_project', models.BooleanField(default=False)),
                ('has_access_to_package_handover', models.BooleanField(default=False)),
                ('has_access_to_asset_handover', models.BooleanField(default=False)),
                ('has_access_to_quality_issue', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
