# Generated by Django 3.2.15 on 2023-07-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0258_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_api_access_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_api_access_allowed',
        ),
    ]
