# Generated by Django 3.2.15 on 2023-07-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0259_remove_api_key_flags_20230704_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='assethandoverdocumentmediaupdate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AddField(
            model_name='packagehandoverdocumentmediaupdate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
