# Generated by Django 3.2.15 on 2023-07-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0260_add_updates_company_20230728_0750'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    UPDATE asset_handover_document_media_updates SET company_id = au.company_id
                    FROM auth_user au
                    WHERE user_id = au.id
                """,
            reverse_sql="""
                            UPDATE asset_handover_document_media_updates SET company_id = null
                        """
        ),
        migrations.RunSQL(
            sql="""
                    UPDATE package_handover_document_media_updates SET company_id = au.company_id
                    FROM auth_user au
                    WHERE user_id = au.id
                """,
            reverse_sql="""
                            UPDATE package_handover_document_media_updates SET company_id = null
                        """
        ),
    ]
