# Generated by Django 3.2.15 on 2023-07-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0261_fill_updates_company_20230728_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assethandoverdocumentmediaupdate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AlterField(
            model_name='packagehandoverdocumentmediaupdate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
