# Generated by Django 3.2.15 on 2023-10-02 12:01

from django.db import migrations, connection


def remove_tasks_with_related_entities(*args, **kwargs) -> None:
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE subtasks
            SET deleted = now()
            FROM tasks t
                     INNER JOIN package_matrix_hidden_activity_tasks pmhat ON pmhat.package_activity_task_id = t.package_activity_task_id
                     INNER JOIN package_matrix pm ON pm.id = pmhat.package_matrix_id
            WHERE t.deleted IS NULL
              AND subtasks.task_id = t.id
              AND pmhat.deleted IS NULL
              AND t.project_id = pm.project_id
              AND pmhat.package_activity_task_id = t.package_activity_task_id
        """)

        cursor.execute("""
            UPDATE quality_issue
            SET deleted = now()
            FROM subtasks s
                     INNER JOIN tasks t ON s.task_id = t.id
                     INNER JOIN package_matrix_hidden_activity_tasks pmhat ON pmhat.package_activity_task_id = t.package_activity_task_id
                     INNER JOIN package_matrix pm ON pm.id = pmhat.package_matrix_id
            WHERE t.deleted IS NULL
              AND quality_issue.id = s.quality_issue_id
              AND pmhat.deleted IS NULL
              AND t.project_id = pm.project_id
              AND pmhat.package_activity_task_id = t.package_activity_task_id
        """)

        cursor.execute("""
            UPDATE tasks
            SET deleted = now()
            FROM package_matrix_hidden_activity_tasks pmhat
                     INNER JOIN package_matrix pm ON pm.id = pmhat.package_matrix_id
            WHERE tasks.deleted IS NULL
              AND pmhat.deleted IS NULL
              AND tasks.project_id = pm.project_id
              AND pmhat.package_activity_task_id = tasks.package_activity_task_id
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0262_remove_updates_company_nullable_property_20230728_0753'),
    ]

    operations = [
        migrations.RunPython(remove_tasks_with_related_entities)
    ]
