# Generated by Django 3.2.15 on 2023-10-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0263_delete_tasks_20231002_1201'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='floorplan',
            name='floor_plans_unique_media',
        ),
        migrations.AddConstraint(
            model_name='floorplan',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('project', 'package', 'building', 'level'), name='floor_plans_unique_media'),
        ),
    ]
