# Generated by Django 3.2.15 on 2023-10-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0265_handover_document_archive_20231023_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
