from api.enums import ChoiceEnum


class Entities(ChoiceEnum):
    COMPANY = 'company'
    LOCATION_MATRIX = 'location_matrix'
    MEDIA = 'media'
    PACKAGE = 'package'
    PACKAGE_ACTIVITY = 'package_activity'
    PACKAGE_ACTIVITY_FILES = 'package_activity_files'
    PACKAGE_ACTIVITY_TASK = 'package_activity_task'
    PACKAGE_MATRIX = 'package_matrix'
    PACKAGE_MATRIX_COMPANY = 'package_matrix_company'
    PROJECT = 'project'
    PROJECT_KEY_CONTACTS = 'project_key_contacts'
    PROJECT_USER = 'project_user'
    QUALITY_ISSUE = 'quality_issue'
    QUALITY_ISSUE_ATTACHMENTS = 'quality_issue_attachments'
    QUALITY_ISSUE_UPDATE = 'quality_issue_update'
    QUALITY_ISSUE_UPDATE_FILES = 'quality_issue_update_files'
    QUALITY_ISSUE_UPDATE_RECIPIENTS = 'quality_issue_update_recipients'
    RECIPIENT = 'recipient'
    SUBTASK = 'subtask'
    SUBTASK_FILES = 'subtask_files'
    SUBTASK_UPDATE = 'subtask_update'
    SUBTASK_UPDATE_FILES = 'subtask_update_files'
    SUBTASK_UPDATE_RECIPIENT = 'subtask_update_recipient'
    TASK = 'task'
    TASK_UPDATE = 'task_update'
    TASK_UPDATE_FILES = 'task_update_files'
    TASK_UPDATE_RECIPIENT = 'task_update_recipient'
    USER = 'user'
    USER_GROUPS = 'user_groups'
