from typing import List

from api.queues.core.base import use_rq_if_configured
from api.queues.rq.handover_document import \
    create_handover_document_from_asset_handover_document_media as create_handover_document_from_asset_handover_document_media_rq, \
    delete_handover_document_on_asset_handover_document_media_delete as delete_handover_document_on_asset_handover_document_media_delete_rq, \
    delete_handover_document_on_asset_handover_delete as delete_handover_document_on_asset_handover_delete_rq, \
    undelete_handover_document_on_asset_handover_undelete as undelete_handover_document_on_asset_handover_undelete_rq, \
    undelete_handover_document_on_package_handover_undelete as undelete_handover_document_on_package_handover_undelete_rq, \
    create_handover_document_from_package_handover_document_media as create_handover_document_from_package_handover_document_media_rq, \
    delete_handover_document_on_package_handover_document_media_delete as delete_handover_document_on_package_handover_document_media_delete_rq, \
    delete_handover_document_on_package_handover_delete as delete_handover_document_on_package_handover_delete_rq, \
    delete_handover_document_on_package_handover_document_delete as delete_handover_document_on_package_handover_document_delete_rq, \
    update_handover_document_on_asset_handover_document_media_update as update_handover_document_on_asset_handover_document_media_update_rq, \
    update_handover_document_on_package_handover_document_media_update as update_handover_document_on_package_handover_document_media_update_rq, \
    update_handover_document_on_location_matrix_update as update_handover_document_on_location_matrix_update_rq, \
    remove_handover_document_on_asset_handover_document_media_update as remove_handover_document_on_asset_handover_document_media_update_rq, \
    remove_handover_document_on_package_handover_document_media_update as remove_handover_document_on_package_handover_document_media_update_rq, \
    create_handover_document_on_asset_handover_document_media_update as create_handover_document_on_asset_handover_document_media_update_rq, \
    create_handover_document_on_package_handover_document_media_update as create_handover_document_on_package_handover_document_media_update_rq, \
    send_email_with_handover_document_archive as send_email_with_handover_document_archive_rq

from api.queues.celery.handover_document import \
    create_handover_document_from_asset_handover_document_media as create_handover_document_from_asset_handover_document_media_celery, \
    delete_handover_document_on_asset_handover_document_media_delete as delete_handover_document_on_asset_handover_document_media_delete_celery, \
    delete_handover_document_on_asset_handover_delete as delete_handover_document_on_asset_handover_delete_celery, \
    undelete_handover_document_on_asset_handover_undelete as undelete_handover_document_on_asset_handover_undelete_celery, \
    undelete_handover_document_on_package_handover_undelete as undelete_handover_document_on_package_handover_undelete_celery, \
    create_handover_document_from_package_handover_document_media as create_handover_document_from_package_handover_document_media_celery, \
    delete_handover_document_on_package_handover_document_media_delete as delete_handover_document_on_package_handover_document_media_delete_celery, \
    delete_handover_document_on_package_handover_delete as delete_handover_document_on_package_handover_delete_celery, \
    delete_handover_document_on_package_handover_document_delete as delete_handover_document_on_package_handover_document_delete_celery, \
    update_handover_document_on_asset_handover_document_media_update as update_handover_document_on_asset_handover_document_media_update_celery, \
    update_handover_document_on_package_handover_document_media_update as update_handover_document_on_package_handover_document_media_update_celery, \
    update_handover_document_on_location_matrix_update as update_handover_document_on_location_matrix_update_celery, \
    remove_handover_document_on_asset_handover_document_media_update as remove_handover_document_on_asset_handover_document_media_update_celery, \
    remove_handover_document_on_package_handover_document_media_update as remove_handover_document_on_package_handover_document_media_update_celery, \
    create_handover_document_on_asset_handover_document_media_update as create_handover_document_on_asset_handover_document_media_update_celery, \
    create_handover_document_on_package_handover_document_media_update as create_handover_document_on_package_handover_document_media_update_celery, \
    send_email_with_handover_document_archive as send_email_with_handover_document_archive_celery

from api.models import AssetHandoverDocumentMedia, AssetHandover, PackageHandoverDocumentMedia, PackageHandover, \
    AssetHandoverDocumentMediaUpdate, PackageHandoverDocumentMediaUpdate, LocationMatrix, Media, User, \
    PackageHandoverDocument


@use_rq_if_configured(create_handover_document_from_asset_handover_document_media_rq)
def create_handover_document_from_asset_handover_document_media(asset_handover_document_media: AssetHandoverDocumentMedia) -> None:
    create_handover_document_from_asset_handover_document_media_celery.delay(asset_handover_document_media)


@use_rq_if_configured(delete_handover_document_on_asset_handover_document_media_delete_rq)
def delete_handover_document_on_asset_handover_document_media_delete(asset_handover_document_media: AssetHandoverDocumentMedia) -> None:
    delete_handover_document_on_asset_handover_document_media_delete_celery.delay(asset_handover_document_media)


@use_rq_if_configured(delete_handover_document_on_asset_handover_delete_rq)
def delete_handover_document_on_asset_handover_delete(asset_handover: AssetHandover) -> None:
    delete_handover_document_on_asset_handover_delete_celery.delay(asset_handover)


@use_rq_if_configured(undelete_handover_document_on_asset_handover_undelete_rq)
def undelete_handover_document_on_asset_handover_undelete(asset_handovers: List[AssetHandover]) -> None:
    undelete_handover_document_on_asset_handover_undelete_celery.delay(asset_handovers)


@use_rq_if_configured(undelete_handover_document_on_package_handover_undelete_rq)
def undelete_handover_document_on_package_handover_undelete(package_handover: PackageHandover) -> None:
    undelete_handover_document_on_package_handover_undelete_celery.delay(package_handover)


@use_rq_if_configured(create_handover_document_from_package_handover_document_media_rq)
def create_handover_document_from_package_handover_document_media(package_handover_document_media: PackageHandoverDocumentMedia) -> None:
    create_handover_document_from_package_handover_document_media_celery.delay(package_handover_document_media)


@use_rq_if_configured(delete_handover_document_on_package_handover_document_media_delete_rq)
def delete_handover_document_on_package_handover_document_media_delete(package_handover_document_media: PackageHandoverDocumentMedia) -> None:
    delete_handover_document_on_package_handover_document_media_delete_celery.delay(package_handover_document_media)


@use_rq_if_configured(delete_handover_document_on_package_handover_delete_rq)
def delete_handover_document_on_package_handover_delete(package_handover: PackageHandover) -> None:
    delete_handover_document_on_package_handover_delete_celery.delay(package_handover)


@use_rq_if_configured(delete_handover_document_on_package_handover_document_delete_rq)
def delete_handover_document_on_package_handover_document_delete(package_handover_document: PackageHandoverDocument) -> None:
    delete_handover_document_on_package_handover_document_delete_celery.delay(package_handover_document)


@use_rq_if_configured(update_handover_document_on_asset_handover_document_media_update_rq)
def update_handover_document_on_asset_handover_document_media_update(asset_handover_document_media_update: AssetHandoverDocumentMediaUpdate) -> None:
    update_handover_document_on_asset_handover_document_media_update_celery.delay(asset_handover_document_media_update)


@use_rq_if_configured(update_handover_document_on_package_handover_document_media_update_rq)
def update_handover_document_on_package_handover_document_media_update(package_handover_document_media_update: PackageHandoverDocumentMediaUpdate) -> None:
    update_handover_document_on_package_handover_document_media_update_celery.delay(package_handover_document_media_update)


@use_rq_if_configured(update_handover_document_on_location_matrix_update_rq)
def update_handover_document_on_location_matrix_update(location_matrices: List[LocationMatrix]) -> None:
    update_handover_document_on_location_matrix_update_celery.delay(location_matrices)


@use_rq_if_configured(remove_handover_document_on_asset_handover_document_media_update_rq)
def remove_handover_document_on_asset_handover_document_media_update(update: AssetHandoverDocumentMediaUpdate) -> None:
    remove_handover_document_on_asset_handover_document_media_update_celery.delay(update)


@use_rq_if_configured(remove_handover_document_on_package_handover_document_media_update_rq)
def remove_handover_document_on_package_handover_document_media_update(update: PackageHandoverDocumentMediaUpdate) -> None:
    remove_handover_document_on_package_handover_document_media_update_celery.delay(update)


@use_rq_if_configured(create_handover_document_on_asset_handover_document_media_update_rq)
def create_handover_document_on_asset_handover_document_media_update(update: AssetHandoverDocumentMediaUpdate) -> None:
    create_handover_document_on_asset_handover_document_media_update_celery.delay(update)


@use_rq_if_configured(create_handover_document_on_package_handover_document_media_update_rq)
def create_handover_document_on_package_handover_document_media_update(update: PackageHandoverDocumentMediaUpdate) -> None:
    create_handover_document_on_package_handover_document_media_update_celery.delay(update)


@use_rq_if_configured(send_email_with_handover_document_archive_rq)
def send_email_with_handover_document_archive(archive: Media, project_id: int, user: User) -> None:
    send_email_with_handover_document_archive_celery.delay(archive, project_id, user)
